### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by nantas** [cocos-creator/firedoc-theme-default-deprecated#1]
和 firedoc 默认主题相比，更改/增加了以下功能：
1. 左边导航栏分级显示内容，module->class->member list
2. 左边导航栏的 scroll 和 正文的 scroll 分开
3. 支持 . 搜索. 比如 Fire.log, 可以搜索出 Fire 底下的 log member
4. 更好的样式标签显示和配色

参考 pixi 的新文档：http://pixijs.github.io/docs/
可以考虑新开一个 repo，作为全新 theme 开发。

**Comment by yorkie** [comment]
新repo就是 [firedoc-theme-default](https://github.com/fireball-x/firedoc-theme-default) 对吗？

**Comment by nantas** [comment]
我再开一个吧，原来的 theme 应该是更适合某些人需要的，可以保留

新theme repo：
https://github.com/fireball-x/firedoc-theme-notab

**Comment by yorkie** [comment]
好
